spring:
  datasource:
    url: jdbc:mysql://my-db:3306/commerce
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
      connection-test-query: SELECT 1 FROM DUAL
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  redis:
    host: my-redis
    port: 6379

  data:
    mongodb:
      uri: mongodb://my-mongodb:27017/adDb
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: user
    password: 1234

logging:
  level:
    root: info
    web: info
    sql: error
    org.springframework: error
    com.commerce.backend: info
    org.hibernate: error
