spring:
  datasource:
    url: jdbc:mysql://localhost:3306/commerce
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
      connection-test-query: SELECT 1 FROM DUAL
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  redis:
    host: localhost
    port: 6379

  data:
    mongodb:
      uri: mongodb://localhost:27017/adDb
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: 1234

#springdoc:
#  swagger-ui:
#    groups-order: DESC
#    tags-sorter: alpha
#    operations-sorter: method
#    disable-swagger-default-url: true
#    display-request-duration: true
#    defaultModelsExpandDepth: 2
#    defaultModelExpandDepth: 2
#  api-docs:
#    path: /api-docs
#  show-actuator: true
#  default-consumes-media-type: application/json
#  default-produces-media-type: application/json
#  writer-with-default-pretty-printer: true
#  model-and-view-allowed: true
#  paths-to-match:
#    - /**



logging:
  level:
    root: info
    web: info
    sql: error
    org.springframework: error
    com.commerce.backend: info
    org.hibernate: error